language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g typescript
  - gem install sass
  - gem install compass
  - npm install -g compass
install:
  - bower install
  - npm install
