language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g typescript
  - gem install sass
  - gem install compass
  - npm install -g compass
install:
  - bower install
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  code_climate:
    repo_token: 85bcaf90b8e403419913869f6ad0f4e93d202a39a7425885b24b68b8fe22833
after_script:
  - codeclimate < coverage/report-lcov/lcov.info
