language: node_js
node_js:
  - "4.3.1"
before_install:
  - npm install -g codeclimate-test-reporter
  - gem install sass
  - gem install compass
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  code_climate:
    repo_token: a85bcaf90b8e403419913869f6ad0f4e93d202a39a7425885b24b68b8fe22833
after_script:
  - codeclimate-test-reporter < coverage/report-lcov/lcov.info
